week06/hit-the-Django/week6/myinsta/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from rest_framework import routers

from posts.views import *
from posts.views import class_view

# router=routers.DefaultRouter()
# router.register('posts', PostModelViewSet)
# router.register('comments', CommentViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    # Function Based View
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view),
    path('fbv/', function_view),
    # Class Based View
    path('cbv/', class_view.as_view()), # as_view: 진입 메소드

    # path('', index, name='index'),
    # path('', include(router.urls)),
    # path('posts/', include('posts.urls', namespace='posts')), #앱.url로 전달
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('posts/',PostListCreateView.as_view(), name='post-list-create'),
    path('posts/',PostListRetrieveUpdateView.as_view(), name='post-detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

week06/hit-the-Django/week6/posts/urls.py
from django.urls import path

from rest_framework.urlpatterns import format_suffix_patterns
from . import views

from .views import post_list_view, post_create_view, post_created_form_view
from .views import post_delete_view, post_detail_view, post_update_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name = 'post-list'),
    # path('create/', post_create_view, name='post-create'),
    path('create/', post_created_form_view, name='post-create'),
    path('<int:id>/', post_detail_view, name='post-detail'),
    path('<int:id>/edit', post_update_view, name='post-update'),
    path('<int:id>/delete', post_delete_view, name='post-delete'),
]

urlpatterns=[
    path('posts/', views.PostList.as_view()),
    path('posts/<int:pk>/', views.PostDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

week06/hit-the-Django/week6/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()

class Post (models.Model):
    image = models.ImageField(verbose_name='이미지', null=True, blank=True)
    content = models.TextField(verbose_name='내용', null=True)
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    view_count = models.IntegerField(verbose_name='조회수', default=0)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='작성자', null=True, blank=True)

class Comment(models.Model):
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    post = models.ForeignKey(to='Post', on_delete=models.CASCADE, verbose_name='게시글')
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='작성자', null=True)

week06/hit-the-Django/week6/posts/forms.py
from django import forms
from .models import Post

class PostBasedForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
    

class PostCreateForm(PostBasedForm):
    class Meta(PostBasedForm.Meta):
        fields = ['image', 'content']

class PostUpdateForm(PostBasedForm):
    class Meta(PostBasedForm.Meta):
        fields = ['image', 'content']

class PostDetailForm(PostBasedForm):
    def __init__(self, *args, **kwargs):
        super(PostDetailForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].widget.attrs['disabled'] = True

week06/hit-the-Django/week6/posts/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponse, JsonResponse, Http404
from rest_framework.viewsets import ModelViewSet
from rest_framework import viewsets
from .serializers import *
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from .models import Post, Comment, Posts
from .forms import PostBasedForm, PostCreateForm, PostDetailForm

from rest_framework import generics

# 게시글 목록
class PostListView(generics.ListAPIView):
    queryset=Post.objects.all()
    serializer_class=PostListModelSerializer

# 게시글 상세
class PostRetrieveView(generics.RetrieveAPIView):
    queryset=Post.objects.all()
    serializer_class=PostRetrieveModelSerializer

# 게시글 목록
class PostListCreateView(generics.ListAPIView, generics.CreateAPIView):
    queryset=Post.objects.all()
    serializer_class=PostModelSerializer

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        #self.perform_create(serializer)
        serializer.save()
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

# 게시글 상세, 수정, 삭제
class PostRetrieveUpdateView(generics.RetrieveAPIView, generics.UpdateAPIView, generics.DestroyAPIView):
    queryset=Post.objects.all()
    serializer_class=PostRetrieveSerializer

class PostModelViewSet(ModelViewSet):
    queryset=Post.objects.all()
    serializer_class=PostListModelSerializer

    #@action(detail=True, methods=['get'])
    #def get_comment_all(self, request, pk=None):
    #    post = self.get_object()
    #    comment_all = post.set_comment.objects.all()
    #    return Response()

# class CommentModelViewSet(ModelViewSet):
#     queryset=Comment.objects.all()
#     serializer_class=CommentHyperlinkedModelSerializer
    



class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

def index(request):
    post_list = Post.objects.all().order_by('-created_at') # Post 모델에 있는 객체 전부 불러오기
    context = {
        'post_list': post_list,
    }
    return render(request, 'index.html', context)

def post_list_view(request):
    # post_list = Post.objects.all() #Post 모델에 있는 객체 전부 불러오기
    post_list = Post.objects.filter(writer=request.user)
    context = { # Post 객체를 리스트 형태로 담기
        'post_list': post_list,
    }
    return render(request, 'posts/post_list.html', context)

def post_detail_view(request, id):
    try:
        post = Post.objects.get(id=id)
    except Post.DoesNotExist: # 존재하지 않는 게시글을 조회할 경우
        return redirect('index') # index.html로 리다이렉트
    post = Post.objects.get(id=id)
    context = {
        'post':post,
        'form' : PostDetailForm(),
    }
    return render(request, 'posts/post_detail.html', context)

@login_required
def post_create_view(request):
    if request.method == 'GET':
        return render(request, 'posts/post_form.html')
    else:
        image = request.FILES.get('image')
        content = request.POST.get('content')
        Post.objects.create( # image, content 데이터를 담은 Post 객체 만들어서 저장
            image = image,
            content = content,
            writer = request.user
        )
        return redirect('index')
# GET은 처음 생성 페이지 들어갔을 때 -> post_form.html 보여주기
# else는 사용자가 폼을 작성하고 제출 버튼을 눌렀을 때 index 페이지 리다이렉트

def post_created_form_view(request):
    if request.method=="GET":
        form = PostCreateForm()
        context = {'form': form}
        return render(request, 'posts/post_form2.html', context)
    else:
        form = PostCreateForm(request.POST, request.FILES)

        if form.is_valid():
            Post.objects.create( #image, content 데이터를 담은 Post 객체 만들어서 저장
            image=form.cleaned_data['image'],
            content=form.cleaned_data['content'],
            writer=request.user
            )
        else:
            return redirect('post:post-create')
        return redirect('index')

    
        return redirect('index')

@login_required
def post_update_view(request, id):

    # post = Post.objects.get(id=id)
    post = get_object_or_404(Post, id=id, writer=request.user)

    if request.method == 'GET':
        context = { 'post':post }
        return render(request, 'posts/post_form.html', context)
    elif request.method == 'POST':
        new_image = request.FILES.get('image')
        content = request.POST.get('content')
        print(new_image)
        print(content)
        if new_image:
            post.image.delete()
            post.image = new_image

        post.image = new_image
        post.content = content
        post.save()
        return redirect('posts:post-detail', post.id)

@login_required
def post_delete_view(request, id):
    post = get_object_or_404(Post, id=id)
    # post = get_object_or_404(Post, id=id, writer=request.user)
    if request.user != post.writer:
        raise Http404('잘못된 접근입니다.')
    
    if request.method == "GET":
        context = { 'post': post }
        return render(request, 'posts/post_confirm_delete.html',context)
    else:
        post.delete()
        return redirect('index')
    
    

class class_view(ListView):
    model = Post
    template_name = 'cbv_view.html'

def url_view(request):
    data = {'code': '001', 'msg': 'OK'}
    return HttpResponse('<h1>url_views</h1>')

def url_parameter_view(request, username):
    print(f'url_parameter_view()')
    print(f'username: {username}')
    print(f'request.GET: {request.GET}')
    return HttpResponse(username)

def function_view(request):
    print(f'request.method: {request.method}')

    if request.method == "GET":
        print(f'request.GET: {request.GET}')
    elif request.method == 'POST':
        print(f'request.POST: {request.POST}')
    return render(request, 'view.html')

week06/hit-the-Django/week6/myinsta/templates/mixin/posts/post_card.html
{% load static %}
<div class="card">
    <div class="card__header">
        <img src="http://via.placeholder.com/32x33" alt="프로필이미지">
        <a href="#">
            <span class="card__user-name">{{ post.writer }}</span>
        </a>
        {% if request.user == post.writer %}
        <a href="{% url 'posts:post-update' post.id %}">수정하기</a> |
        <a href="{% url 'posts:post-delete' post.id %}">삭제하기</a>
        {% endif %}
    </div>
    <div class="card__body">
        <div>
            <!-- 이미지가 있는 경우 -->
            {% if post.image %}
                <img class="card__image" src="{{ post.image.url }}" alt="피드이미지">
            <!-- 이미지가 없는 경우 -->
            {% else %}
            <img class="card__image" src="http://via.placeholder.com/450x450" alt="피드이미지">
            {% endif %}
        </div>
    </div>
    <div class="card__btn-group">
        <div>
            <img class="card__btn" src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요">
            <img class="card__btn" src="{% static 'icons/mode_comment_outlined_black_36dp.svg' %}" alt="댓글">
            <img class="card__btn" src="{% static 'icons/send_outlined_black_36dp.svg' %}" alt="공유하기">
        </div>
        <div>
            <img class="card__btn" src="{% static 'icons/bookmark_outlined_black_36dp.svg' %}" alt="북마크">
        </div>
    </div>
    <div class="card_content">
        <span class="card__like-num">좋아요 00개</span>
        <div class="card__main-text">
            <p><span class="card__user-name">{{ post.writer }}</span>
                <!-- list 보기인 경우 잘린 본문 표시 -->
                {% if not detail %}
                    {{post.content|truncatechars:35}}
                <!-- 상세 보기인 경우 전체 본문 표시 -->
                {% else %}
                    {{post.content}}
                {% endif %}
            </p>
            <!-- list 보기인 경우 더보기 버튼 노출 -->
            {% if not detail %}
                <a href="{% url 'posts:post-detail' post.id %}"> 더보기 </a>
            {% endif %}
        </div>
        <div>
            <!-- Post는 Comment를 역참조하기 때문에, 이런 식의 템플릿 변수를 사용할 수 있어요. -->
            <p>댓글 {{ post.comment_set.all.count }}개
                {% if not detail %}
                    <a href="{% url 'posts:post-detail' post.id %}">모두 보기</a>
                {% endif %}
            </p>
            <ul class="card__comment-group">
                {% if not detail %}
                    {% for comment in post.comment_set.all|slice:":2" %}
                <li>
                    <p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                </li>
                    {% endfor %}
                {% else %}
                    {% for comment in post.comment_set.all %}
                    <li>
                        <p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                    </li>
                    {% endfor %}
                {% endif %}
            </ul>
            <p class="card__created-at">{{ post.created_at|date:"Y년 m월 d일"}}</p>
        </div>
    </div>
</div>